### ISSUE TITLE
[TC-219] CRUD Delivery Service - Self Service

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#971] opened 2017-08-29 12:44 UTC
<p>Allow customers to CRUD delivery services via the API and Portal accessing all available features and configurations.</p>

Author: Ashish Timilsina
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-219">https://issues.apache.org/jira/browse/TC-219</a>

**Comment by mitchell852** [comment] 2017-09-26 15:54
duplicate of #1254

**Closed by mitchell852** 2017-09-26 15:54 UTC
Labels: Configuration, major, new feature, self_service, Traffic Ops, Traffic Portal
