### ISSUE TITLE
[TC-422] TPv2 - add the ability to export/import profiles

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#1058] opened 2017-08-29 13:02 UTC
<p>In order to achieve feature parity with the existing TO UI, the ability to export/import profiles needs to be added to TP.</p>

Author: Jeremy Mitchell
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-422">https://issues.apache.org/jira/browse/TC-422</a>

**Comment by mitchell852** [comment] 2017-09-26 16:02
duplicate of #1283

**Closed by mitchell852** 2017-09-26 16:02 UTC
Labels: improvement, minor, Traffic Portal
