### ISSUE TITLE
[TC-424] TPv2 - add the ability to dump the TO schema and data

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#1057] opened 2017-08-29 13:02 UTC
<p>In order to achieve feature parity with the existing TO UI, add the ability to dump the TO schema and data to a file leveraging the /api/$version/dbdump api endpoint.</p>

Author: Jeremy Mitchell
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-424">https://issues.apache.org/jira/browse/TC-424</a>

**Comment by mitchell852** [comment] 2017-09-26 16:01
duplicate of #1287

**Closed by mitchell852** 2017-09-26 16:01 UTC
Labels: improvement, minor, Traffic Portal
