### ISSUE TITLE
[TC-455] TPv2 - add custom delivery service graph link

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#1048] opened 2017-08-29 13:01 UTC
<p>Add the ability to optionally display a graph icon on a delivery service page that links to a host responsible for displaying graphs for a delivery service. For example, the link may link to</p>

<p><a href="https://the-place-where-grafana-runs.com?ds=xml-id" class="external-link" rel="nofollow">https://the-place-where-grafana-runs.com?ds=xml-id</a></p>

<p>following this link will open a new tab. this is very similar to the link provided in the old TO UI that links to the value of the deliveryservice_graph_url parameter, however, TPv2 is unlike the old TO UI in the sense that it stores setting in traffic_portal_properties.json rather than in global TO parameters.</p>

Author: Jeremy Mitchell
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-455">https://issues.apache.org/jira/browse/TC-455</a>

**Comment by mitchell852** [comment] 2017-11-28 15:13
duplicate of #1051

**Closed by mitchell852** 2017-11-28 15:13 UTC
Labels: improvement, minor, Traffic Portal
