### ISSUE TITLE
[TC-217] CRUD Tenant - Self-service

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#969] opened 2017-08-29 12:44 UTC
<p>Allow users to CRUD sub tenants below their tenant level or below any sub-tenant level they choose. Default would be directly below the current tenant value.</p>

Author: Ashish Timilsina
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-217">https://issues.apache.org/jira/browse/TC-217</a>

**Comment by mitchell852** [comment] 2017-09-26 15:55
duplicate of #1265

**Closed by mitchell852** 2017-09-26 15:55 UTC
Labels: Configuration, major, new feature, self_service, Traffic Ops
