### ISSUE TITLE
Traffic Monitor crashes when CRConfig is absent on TrafficOps

### ISSUE THREAD

**Issue by villajo** [apache/incubator-trafficcontrol#2383] opened 2018-06-08 20:00 UTC
Version tested: traffic_monitor-2.3.0.*

Description: 

Traffic Monitor will crash with a very nasty golang stacktrace if the CRConfig is not installed on the TrafficOps server. The case I ran into is on a fresh CDN install. 

How to replicate: 

Create fresh install of Traffic Ops or Delete CRConfig, do not configure CR. Go to URL https://{TrafficOpsHost}/CRConfig-Snapshots/kabletown_cdn/CRConfig.json. You should see only "{ }" for your CRConfig.json file. 

Start Traffic Monitor, make sure that if it's a local configuration with self signed certificate, that you use the "insecure" : true option.

**Comment by rob05c** [comment] 2018-06-08 20:03
Duplicate of https://github.com/apache/incubator-trafficcontrol/issues/2383
Should be fixed by https://github.com/apache/incubator-trafficcontrol/pull/2377

**Comment by rob05c** [comment] 2018-06-08 21:07
Ok, #2377 has been merged. Can you try building from master, and if it still happens, reopen this with details?

In particular, if it happens again, can you paste the stacktrace here? That would really help track it down. Thanks!

**Closed by rob05c** 2018-06-08 21:07 UTC
