### ISSUE TITLE
No delivery service prefix after upgrading to 2.2

### ISSUE THREAD

**Issue by smalenfant** [apache/incubator-trafficcontrol#1630] opened 2017-12-08 13:20 UTC
Upgraded to 2.2 and lost all my delivery service prefixes (edge,tr). Looking at the code, seems like dbadmin never gets invoked with `patch` so the `patches.sql` never gets run.

**Comment by smalenfant** [comment] 2017-12-08 13:25
As a workaround, please run this after upgrade.

```
# export PERL5LIB=/opt/traffic_ops/app/lib:/opt/traffic_ops/app/local/lib/perl5
# cd /opt/traffic_ops/app
# ./db/admin.pl --env=production patch
```

**Comment by smalenfant** [comment] 2017-12-08 13:59
In addition, seems like setting `upgrade_http_routing_name` doesn't work as intended. That should be a separate issue but it's part of the same process. I've tried putting my customer name parameter on the CCR, Edge and DS Profile, but still ended with `tr`.

**Comment by rawlinp** [comment] 2017-12-08 17:08
Originally the DB upgrade step was attempted during the `yum upgrade traffic_ops` step, but it always failed due to the way PATH was hardcoded. So I took it out and documented it as a required manual step (#871) because our ops team had become accustomed to doing that step manually already due to it failing in the `yum upgrade traffic_ops` step. It doesn't show up on [the latest published docs](https://trafficcontrol.incubator.apache.org/docs/latest/admin/traffic_ops/installation.html#upgrading-traffic-ops) yet I'm guessing because 2.1 hasn't been released yet, but this is in master:

> Upgrading Traffic Ops
> To upgrade:
> 
> 1. Enter the following command: `service traffic_ops stop`
> 2. Enter the following command: `yum upgrade traffic_ops`
> 3. Enter the following command from the /opt/traffic_ops/app directory: `PERL5LIB=/opt/traffic_ops/app/lib:/opt/traffic_ops/app/local/lib/perl5 ./db/admin.pl --env production upgrade`
> 4. See Traffic Ops - Installing to run postinstall.
> 5. Enter the following command: `service traffic_ops start`

I know having another required manual step is not ideal, so it would probably be worth it to fix the `yum upgrade traffic_ops` step to upgrade the DB properly and remove the manual step. It would just require fixing the `migratedb` script to use the PATH where goose *should* be installed, but I believe the location of the `goose` binary install had changed at least once, which was basically a breaking change for `migratedb`. So it's safest to just run it manually where hopefully the `goose` binary will be found on your PATH (in case it was installed in a previous location).

About `upgrade_http_routing_name` not working as intended, I'm really curious as to why. The profile you're assigning it to is associated to a CDN right? Do you have the fields mixed up? Parameter details should look like this:
```
Name: upgrade_http_routing_name
Config File: temp
Value: <insert custom routing name here>

Used in the following profiles:
FOO_TR_PROFILE          TR profile for the FOO cdn
```
And the Profile details for FOO_TR_PROFILE should have a valid CDN name in the CDN field.

**Comment by smalenfant** [comment] 2017-12-08 17:12
I just found out why the `upgrade_http_routing_name` didn't work. There was a blank space in front of it, so the SQL query would never find it. That's all good now.

**Comment by rawlinp** [comment] 2017-12-08 17:26
Sweet, good to know.

**Comment by mitchell852** [comment] 2017-12-19 15:01
@smalenfant - can this be closed?

**Comment by smalenfant** [comment] 2017-12-19 15:10
@mitchell852 Can we merge #1633 ?

**Comment by mitchell852** [comment] 2017-12-19 15:19
oh ok, didn't realize there was a PR attached to this issue. i need to look closer in the future. looking at PR...

**Closed** 2017-12-19 15:42 UTC
Labels: bug, critical, Traffic Ops
